### ISSUE TITLE
HomeBridge V2 Support

### ISSUE THREAD

**Issue by Marco674** [julienott/homebridge-heatzy-pilote-platform#1]
Hi there, 

Love the plugin ❤️ 

Homebridge V2 is around the corner and i wanted to know if the plugin is / will be compatible
![image](https://github.com/user-attachments/assets/9ccf81cd-d5d6-45ff-ab91-588aaedd171e)

Thank you

**Comment by julienott** [comment]
Hello Marco, thanks for the message!
Yes indeed I’m currently updating it, I’m slow but will ultimately publish it within 2 weeks.

Best,

Julien

**Comment by julienott** [comment]
Should be ok now!
